# -*- coding: utf-8 -*-
"""The question text of each worked example, re-typed from the source.

The original typist pasted every question as a picture of itself. A picture
cannot be searched, resized or corrected, and the brief asks for the prompts
as text, so each one was read off the image and written out here: Kurdish as
Kurdish, the maths as LaTeX between dollar signs.

Keyed by the image the question replaced. A value of None marks a picture
that turned out to be a banner or a law, not a question.
"""

P = {
    # ------------------------------------------------------------- بەشی ٥
    '5/image58.png':  ('پێوانەی گۆشەی ', r'$\hat{A}$', ' چەندە؟'),
    '5/image59.png':  ('درێژی ژێیەکەی چەندە؟',),
    '5/image60.png':  ('درێژی ', r'$\overline{BC}$', ' چەندە؟'),
    '5/image89.png':  (r'$\frac{12}{\sin(102)}=\frac{x}{\sin(41)}$',),
    '5/image90.png':  (r'$\frac{15}{\sin(43)}=\frac{17}{\sin\hat{x}}$',),
    '5/image101.png': ('پێوانەی گۆشەی N چەندە؟',),
    '5/image121.png': ('ڕووبەری ئەم سێگۆشەیەی خوارەوە هەژمار بکە.',),
    '5/image125.png': ('ڕووبەری چوارلای بەرامبەر چەندە؟',),

    # ------------------------------------------------------------- بەشی ٦
    '6/image7.png':   (r'$y=3x-1$',),
    '6/image8.png':   (r'$2x-y=3$',),
    '6/image9.png':   (r'$4y-2x=12$',),
    '6/image11.png':  (r'$y=0.5x-2$',),
    '6/image12.png':  (r'$3x-y=1$',),
    '6/image13.png':  (r'$3y-6x=15$',),
    '6/image16.png':  None,   # banner: یاسای سێیەم
    '6/image18.png':  None,   # the chain rule, written out as a picture
    '6/image24.png':  (r'$f(x)=3x^{2}+5x-1$',),
    '6/image25.png':  (r'$f(x)=2\sin 3x+7x$',),
    '6/image26.png':  (r'$f(x)=3\cos x-e^{2x}$',),
    '6/image28.png':  (r'$f(x)=2x^{3}+x^{2}-5$',),
    '6/image29.png':  (r'$f(x)=3\sin 5x-2x$',),
    '6/image30.png':  (r'$f(x)=\cos 3x+e^{3x}$',),
    '6/image32.png':  (r'$f(x)=(3x+2)^{4}$',),
    '6/image33.png':  (r'$f(x)=(\sin x+e^{x})^{3}$',),
    '6/image35.png':  (r'$f(x)=(x^{2}+5x)^{2}$',),
    '6/image36.png':  (r'$f(x)=(\cos x+2e^{x})^{5}$',),
    '6/image44.png':  (r'$f(x)=3x+1$',),
    '6/image46.png':  (r'$f(x)=x^{2}+x+2$',),
    '6/image52.png':  (r'$(1,8)\ ,\ (7,-4)$',),
    '6/image53.png':  (r'$(0,1)\ ,\ (4,1)$',),
    '6/image54.png':  (r'$\left(\frac{1}{2},2\right),\left(\frac{1}{2},9\right)$',),
    '6/image56.png':  (r'$y=3-2x$',),
    '6/image57.png':  (r'$2x-3y=6$',),
    '6/image62.png':  (r'$f(x)=\sqrt{x+1}$',),
    '6/image63.png':  (r'$f(x)=-\frac{3}{x^{5}}$',),
    '6/image64.png':  (r'$f(x)=\sqrt{5}$',),
    '6/image71.png':  (r'$f(x)=2x^{-5}$',),
    '6/image72.png':  (r'$f(x)=\cos\left(\frac{1}{3}x\right)$',),
    '6/image73.png':  (r'$f(x)=\sin(x^{2})$',),
    '6/image74.png':  (r'$f(x)=\ln(2-x)$',),
    '6/image75.png':  (r'$f(x)=e^{x^{3}}$',),
    '6/image78.png':  (r'$y=(2x-1)^{5}$',),
    '6/image80.png':  (r'$y=\sin(x^{2}+1)$',),
    '6/image82.png':  (r'$y=\cos(2x+5)$',),
    '6/image86.png':  (r'$f(x)=(2x^{3}+2x+1)^{2}$',),
    '6/image87.png':  (r'$f(x)=(\sin x+2x)^{7}$',),
    '6/image88.png':  (r'$f(x)=5x^{4}+3x^{3}+2x-7$',),
    '6/image89.png':  (r'$f(x)=(\cos x+x)^{4}$',),
    '6/image90.png':  (r'$f(x)=\frac{4}{x^{5}}$',),
    '6/image96.png':  (r'$f(x)=6$',),
    '6/image98.png':  (r'$f(x)=x^{2}-x+1$',),

    # ------------------------------------------------------------- بەشی ٧
    '7/image8.png':   ('ئاراستەبڕی ', r'$\overrightarrow{AB}$'),
    '7/image9.png':   ('ئاراستەبڕی ', r'$\overrightarrow{CD}$'),
    '7/image10.png':  ('ئاراستەبڕی ', r'$\overrightarrow{EF}$'),
    '7/image11.png':  ('ئاراستەبڕی ', r'$\overrightarrow{GH}$'),
    '7/image20.png':  ('درێژی ئاراستەبڕی بەرامبەر بدۆزەرەوە.',),
    '7/image25.png':  (r'$\overrightarrow{AB}=\langle -1,5\rangle$',),
    '7/image27.png':  (r'$\overrightarrow{ED}=\langle 1,4\rangle$',),
    '7/image29.png':  (r'$\overrightarrow{FG}=\langle -2,0\rangle$',),
    '7/image36.png':  None,   # banner: خێرایی ئاراستەبڕ
    '7/image49.png':  (r'$\overrightarrow{AB}=\langle 2,3\rangle$',),
    '7/image50.png':  (r'$\overrightarrow{NO}=\langle 0,5\rangle$',),
    '7/image51.png':  (r'$\overrightarrow{CD}=\langle -1,3\rangle$',),
    '7/image55.png':  (r'$\overrightarrow{EF}=\langle 2,4\rangle$',),
    '7/image56.png':  (r'$\overrightarrow{GH}=\langle 7,1\rangle$',),
    '7/image57.png':  (r'$\overrightarrow{MW}=\langle -2,0\rangle$',),
    '7/image62.png':  (r'$\bar{a}=\langle 1,3\rangle$',),
    '7/image63.png':  (r'$\bar{b}=\langle -2,1\rangle$',),
    '7/image70.png':  (r'$\overrightarrow{AB}=\langle 2,5\rangle$',),
    '7/image71.png':  (r'$\overrightarrow{CD}=\langle 3,1\rangle$',),
    '7/image72.png':  (r'$\overrightarrow{EF}=\langle 1,2\rangle$',),
    '7/image81.png':  (r'$A(4,6)\ ,\ B(-2,-3)$',),
    '7/image82.png':  (r'$A(5,10)\ ,\ B(15,40)$',),
    '7/image84.png':  (r'$A(3,7)\ ,\ B(9,21)$',),
    '7/image85.png':  (r'$A(-6,4)\ ,\ B(-12,16)$',),
    '7/image102.png': (r'$\overrightarrow{AS}=\cdots\overrightarrow{AG}$',),
    '7/image103.png': (r'$\overrightarrow{MN}=\cdots\overrightarrow{KO}$',),
    '7/image104.png': (r'$\overrightarrow{RT}=\cdots\overrightarrow{FJ}$',),
    '7/image105.png': (r'$\overrightarrow{CO}=\cdots\overrightarrow{QE}$',),
    '7/image107.png': (r'$\overrightarrow{CW}=\cdots\overrightarrow{HR}$',),
    '7/image108.png': (r'$\overrightarrow{IO}=\cdots\overrightarrow{AY}$',),
    '7/image109.png': (r'$\overrightarrow{KN}=\cdots\overrightarrow{FI}$',),
    '7/image112.png': (r'$A(1,4)\ ,\ B(2,8)$',),
    '7/image113.png': (r'$C(3,4)\ ,\ D(6,12)$',),
    '7/image114.png': (r'$E(2,5)\ ,\ F(-6,-15)$',),
    '7/image117.png': (r'$\overrightarrow{AJ}=\cdots\overrightarrow{AD}$',),
    '7/image118.png': (r'$\overrightarrow{DE}=\cdots\overrightarrow{DI}$',),
    '7/image120.png': (r'$\overrightarrow{JM}=\cdots\overrightarrow{AM}$',),
    '7/image121.png': (r'$\overrightarrow{AB}=\cdots\overrightarrow{BN}$',),
    '7/image122.png': (r'$\overrightarrow{MD}=\cdots\overrightarrow{MG}$',),
    '7/image123.png': (r'$\overrightarrow{KL}=\cdots\overrightarrow{NF}$',),
    '7/image124.png': (r'$\overrightarrow{FC}=\cdots\overrightarrow{MN}$',),
    '7/image125.png': (r'$\overrightarrow{AB}=\cdots\overrightarrow{MN}$',),
    '7/image137.png': (r'$\overrightarrow{DA}+\overrightarrow{AC}+\overrightarrow{CB}$',),
    '7/image138.png': (r'$\overrightarrow{AC}+\overrightarrow{CE}$',),
    '7/image139.png': (r'$\overrightarrow{DE}+\overrightarrow{EB}$',),
    '7/image161.png': (r'$a-b-c$',),
    '7/image165.png': (r'$\overrightarrow{ED}+\overrightarrow{DB}$',),
    '7/image166.png': (r'$\overrightarrow{DC}+\overrightarrow{CA}+\overrightarrow{AE}$',),
    '7/image167.png': (r'$\overrightarrow{BA}+\overrightarrow{AD}+\overrightarrow{DB}$',),
    '7/image168.png': (r'$\overrightarrow{AB}+\overrightarrow{BC}$',),
    '7/image169.png': (r'$\overrightarrow{BC}+\overrightarrow{CD}+\overrightarrow{DA}$',),
    '7/image172.png': (r'$c+3a$',),
    '7/image175.png': (r'$3c+4d$',),
    '7/image183.png': (r'$a-2b$',),
    '7/image227.png': (r'$\left|b\right|=3\ ,\ \left|a\right|=?$',),
    '7/image228.png': (r'$\left|b\right|=?\ ,\ \left|a\right|=4$',),
    '7/image229.png': (r'$\left|b\right|=\frac{1}{2}\ ,\ \left|a\right|=?$',),
    '7/image232.png': (r'$a=\langle 2,1\rangle$', ' و ', r'$b=\langle 3,-6\rangle$'),
    '7/image233.png': (r'$a=\langle 3,-4\rangle$', ' و ', r'$b=\langle 12,9\rangle$'),

    # Questions the source set as small pictures beside the working. The
    # same treatment as the block above; these were narrow enough to pass
    # for diagrams until they were looked at.
    '5/image28.png':  (r'$125°$',),
    '5/image29.png':  (r'$315°$',),
    '5/image30.png':  (r'$-97°$',),
    '5/image31.png':  (r'$245°$',),
    '5/image33.png':  (r'$215°$',),
    '5/image34.png':  (r'$-100°$',),
    '5/image35.png':  (r'$350°$',),
    '5/image36.png':  (r'$135°$',),
    '5/image46.png':  (r'$\sin\left(\frac{\pi}{4}\right)$',),
    '5/image47.png':  (r'$\cos\left(\frac{2\pi}{3}\right)$',),
    '5/image48.png':  (r'$\tan\left(\frac{3\pi}{4}\right)$',),
    '5/image50.png':  (r'$\tan\left(\frac{4\pi}{3}\right)$',),
    '5/image51.png':  (r'$\cos\left(\frac{5\pi}{6}\right)$',),
    '5/image52.png':  (r'$\sin\left(\frac{2\pi}{3}\right)$',),

    '7/image13.png':  (r'$\overrightarrow{AB}$',),
    '7/image15.png':  (r'$\overrightarrow{GH}$',),
    '7/image16.png':  (r'$\overrightarrow{EF}$',),
    '7/image17.png':  (r'$\overrightarrow{CD}$',),
    '7/image41.png':  (r'$a$',),
    '7/image44.png':  (r'$c$',),
    '7/image45.png':  (r'$d$',),
    '7/image46.png':  (r'$e$',),
    '7/image47.png':  (r'$f$',),
    '7/image65.png':  (r'$\bar{a}$',),
    '7/image67.png':  (r'$\bar{b}$',),
    '7/image68.png':  (r'$\bar{c}$',),
    '7/image92.png':  (r'$2v$',),
    '7/image93.png':  (r'$\frac{1}{2}v$',),
    '7/image94.png':  (r'$-3v$',),
    '7/image96.png':  (r'$5v$',),
    '7/image97.png':  (r'$\frac{1}{3}v$',),
    '7/image98.png':  (r'$-2v$',),
    '7/image145.png': (r'$a+b$',),
    '7/image146.png': (r'$3b+c$',),
    '7/image147.png': (r'$a+2c$',),
    '7/image149.png': (r'$a+2b$',),
    '7/image150.png': (r'$b+3c$',),
    '7/image151.png': (r'$\frac{1}{3}a+c$',),
    '7/image160.png': (r'$3c-a$',),
    '7/image171.png': (r'$a+2b$',),
    '7/image173.png': (r'$d+\frac{1}{2}b$',),
    '7/image174.png': (r'$\frac{1}{3}a+2b$',),
    '7/image176.png': (r'$\frac{2}{3}c+d$',),
    '7/image177.png': (r'$\frac{2}{5}a+\frac{1}{3}d$',),
    '7/image178.png': (r'$\frac{1}{4}d+\frac{3}{2}b$',),
    '7/image181.png': (r'$\frac{1}{2}d-3a$',),
    '7/image184.png': (r'$\frac{4}{3}b-d$',),
    '7/image191.png': (r'$y+z$',),
    '7/image197.png': (r'$a\cdot b$',),
    '7/image198.png': (r'$a\cdot a$',),
    '7/image200.png': (r'$a\cdot b$',),
    '7/image201.png': (r'$b\cdot a$',),
    '7/image202.png': (r'$b\cdot b$',),
    '7/image212.png': (r'$a\cdot b$',),
    '7/image213.png': (r'$d\cdot a$',),
    '7/image214.png': (r'$b\cdot c$',),
    '7/image215.png': (r'$b\cdot b$',),
    '7/image216.png': (r'$a\cdot a$',),
    '7/image217.png': (r'$a\cdot c$',),
    '7/image218.png': (r'$c\cdot c$',),
    '7/image219.png': (r'$d\cdot c$',),
    '7/image222.png': (r'$\theta=45°$',),
    '7/image223.png': (r'$\theta=60°$',),
    '7/image224.png': (r'$\theta=90°$',),
    '7/image225.png': (r'$\theta=30°$',),
}


def lookup(images):
    """The re-typed question for a cell, given the pictures it carried."""
    for name in images:
        if name in P:
            return P[name]
    return None
