; ڕێکخستنی PHP بۆ وەشانی «هەموو ویندۆزەکان» (32-bit، ویندۆز 7 و نوێتر)
extension_dir = "ext"
extension = pdo_sqlite
extension = sqlite3
memory_limit = 256M
max_execution_time = 180
upload_max_filesize = 50M
post_max_size = 60M
date.timezone = Asia/Baghdad
display_errors = Off
log_errors = Off
default_charset = "UTF-8"
